const express=require('express'),request=require('supertest'),mongoose=require('mongoose'),multer=require('multer');
const install=require('../eviction-cases');
const mid='111111111111111111111111',tid='222222222222222222222222',pid='333333333333333333333333',cid='444444444444444444444444';
function setup(){
 const c={_id:cid,managerId:mid,projectId:pid,tenantId:tid,active:true,stage:'review',hold:'active',revision:2,entries:[],audit:[]};
 const Case={findOne:jest.fn(q=>({lean:async()=>q.active?null:c})),init:jest.fn(async()=>{}),create:jest.fn(async x=>({_id:cid,...x})),findOneAndUpdate:jest.fn(async(q,u)=>({...c,...u.$set,revision:3})),find:jest.fn(()=>({select:()=>({sort:()=>({lean:async()=>[]})})}))};
 const File={exists:jest.fn(async()=>false)};
 const Tenant={findById:jest.fn(()=>({lean:async()=>({_id:tid,projectId:pid,leaseType:'fmr',name:'Tenant'})}))};
 const Project={findById:jest.fn(()=>({lean:async()=>({_id:pid,name:'Property',address:{state:'TX'}})}))};
 const Expense={findOneAndUpdate:jest.fn(async(q,u)=>({_id:q._id,...u.$setOnInsert})),findOne:jest.fn(()=>({lean:async()=>null}))};
 const Manager={findById:()=>({select:()=>({lean:async()=>({_id:mid,name:'Manager'})})})};
 const db={Schema:mongoose.Schema,Types:mongoose.Types,isValidObjectId:mongoose.isValidObjectId,model:name=>name==='EvictionCase'?Case:File};
 const app=express();app.use(express.json());install({app,mongoose:db,Tenant,Project,Expense,Manager,multer,authenticateManagerProfile:(req,res,next)=>{if(req.headers.authorization!=='Bearer test')return res.status(401).json({error:'Sign in required.'});req.profileManagerId=mid;next();}});
 return{app,Case,File,Tenant,Expense,c};
}
test('case endpoints work without manager authentication',async()=>{const {app}=setup();expect((await request(app).get('/api/eviction-cases')).status).toBe(200);});
test('case lookup uses shared case identity',async()=>{const {app,Case}=setup();expect((await request(app).get('/api/eviction-cases/'+cid).set('Authorization','Bearer test')).status).toBe(200);expect(Case.findOne).toHaveBeenCalledWith({_id:cid});});
test('Section 8 cases are rejected server-side',async()=>{const {app,Tenant,Case}=setup();Tenant.findById.mockReturnValue({lean:async()=>({_id:tid,projectId:pid,leaseType:'section8'})});const res=await request(app).post('/api/eviction-cases').set('Authorization','Bearer test').send({tenantId:tid,privateMarketConfirmed:true,reason:'nonpayment',owner:'Manager',county:'Bexar',precinct:'1'});expect(res.status).toBe(400);expect(Case.create).not.toHaveBeenCalled();});
test('case creation does not mutate tenant occupancy or charges',async()=>{const {app,Case}=setup();const res=await request(app).post('/api/eviction-cases').set('Authorization','Bearer test').send({tenantId:tid,privateMarketConfirmed:true,reason:'nonpayment',owner:'Manager',county:'Bexar',precinct:'1'});expect(res.status).toBe(201);expect(Case.create.mock.calls[0][0].managerId).toBe(null);});
test('stale revisions cannot overwrite a case',async()=>{const {app,Case}=setup();const res=await request(app).patch('/api/eviction-cases/'+cid).set('Authorization','Bearer test').send({revision:1,nextAction:'Changed'});expect(res.status).toBe(409);expect(Case.findOneAndUpdate).not.toHaveBeenCalled();});
test('foreign document references cannot be attached',async()=>{const {app,Case}=setup();const res=await request(app).post('/api/eviction-cases/'+cid+'/entries').set('Authorization','Bearer test').send({revision:2,kind:'communication',title:'Call',documentId:'555555555555555555555555'});expect(res.status).toBe(400);expect(Case.findOneAndUpdate).not.toHaveBeenCalled();});
test('foreign property expense links are rejected',async()=>{const {app,Case}=setup();const res=await request(app).post('/api/eviction-cases/'+cid+'/entries').set('Authorization','Bearer test').send({revision:2,kind:'expense',title:'Filing',category:'filing',expenseId:'555555555555555555555555'});expect(res.status).toBe(400);expect(Case.findOneAndUpdate).not.toHaveBeenCalled();});
test('task completion appends a version and audit record',async()=>{const {app,Case,c}=setup();c.entries=[{_id:'task1',kind:'task',title:'Call attorney',owner:'Manager',dueAt:'2026-10-01',status:'open'}];const res=await request(app).post('/api/eviction-cases/'+cid+'/tasks/task1/complete').set('Authorization','Bearer test').send({revision:2});expect(res.status).toBe(200);const update=Case.findOneAndUpdate.mock.calls[0][1];expect(update.$push.entries.status).toBe('completed');expect(update.$push.entries.supersedes).toBe('task1');expect(update.$push.audit.action).toBe('Task completed');});

 test('production registers case routes before catch-all',()=>{const s=require('fs').readFileSync(require('path').join(__dirname,'../server.js'),'utf8');expect(s.indexOf("require('./eviction-cases')")).toBeLessThan(s.indexOf('// 404 Fallback Route'));});

const expenseBody={creationId:'666666666666666666666666',revision:2,title:'Court filing',vendor:'County clerk',category:'filing',amount:125,occurredAt:'2026-09-30'};
test('new case expense is linked to property ledger awaiting review',async()=>{const {app,Expense,Case}=setup();const r=await request(app).post('/api/eviction-cases/'+cid+'/expenses').send(expenseBody);expect(r.status).toBe(200);const data=Expense.findOneAndUpdate.mock.calls[0][1].$setOnInsert;expect(data.status).toBe('pending_review');expect(data.lineItems[0]).toMatchObject({projectId:pid,amount:125});expect(Case.findOneAndUpdate.mock.calls[0][1].$push.entries.expenseId).toBe(expenseBody.creationId);});
test.each([{amount:''},{occurredAt:null},{amount:-1},{documentId:'555555555555555555555555'},{revision:1}])('invalid or stale expense cannot create a ledger record: %j',async patch=>{const {app,Expense}=setup();const r=await request(app).post('/api/eviction-cases/'+cid+'/expenses').send({...expenseBody,...patch});expect(r.status).toBeGreaterThanOrEqual(400);expect(Expense.findOneAndUpdate).not.toHaveBeenCalled();});
test('retry of linked expense does not duplicate ledger record',async()=>{const {app,Expense,c}=setup();c.entries=[{kind:'expense',expenseId:expenseBody.creationId}];const r=await request(app).post('/api/eviction-cases/'+cid+'/expenses').send(expenseBody);expect(r.status).toBe(200);expect(Expense.findOneAndUpdate).not.toHaveBeenCalled();});
test('closed case cannot create expense',async()=>{const {app,Expense,c}=setup();c.active=false;expect((await request(app).post('/api/eviction-cases/'+cid+'/expenses').send(expenseBody)).status).toBe(400);expect(Expense.findOneAndUpdate).not.toHaveBeenCalled();});
